"""Documentation generator."""

import ast
import json
import os
from collections import Counter, defaultdict
from pathlib import Path
from typing import TYPE_CHECKING, Any, Dict, List, Optional, Set, Tuple

if TYPE_CHECKING:
    from know.config import Config
    from know.scanner import APIRoute


class DocGenerator:
    """Generates documentation from codebase structure."""
    
    def __init__(self, config: "Config"):
        self.config = config
        self.output_dir = config.root / config.output.directory

    @staticmethod
    def _to_int(value: Any, default: int = 0) -> int:
        """Best-effort numeric conversion for loose structure payloads."""
        try:
            return int(value)
        except (TypeError, ValueError):
            return default
    
    def generate_all(self) -> None:
        """Generate all documentation."""
        from know.scanner import CodebaseScanner
        
        scanner = CodebaseScanner(self.config)
        structure = scanner.get_structure()
        
        # Generate each type of doc
        self.generate_system_doc(structure)  # Default: docs/arc.md
        self.generate_c4_diagram(structure)
        
        routes = scanner.extract_api_routes()
        if routes:
            self.generate_openapi(routes)
    
    def generate_system_doc(self, structure: Dict[str, Any], output: Optional[str] = None) -> Path:
        """Generate system documentation (arc.md or similar)."""
        lines = [
            f"# {self.config.project.name}",
            "",
            self._build_evidence_intro(structure),
            "",
            "## 📁 Project Structure",
            "",
        ]

        modules = list(structure.get("modules", []))
        ranked_modules = sorted(
            modules,
            key=lambda m: (
                self._to_int(m.get("function_count", 0))
                + self._to_int(m.get("class_count", 0)),
                str(m.get("name", "")),
            ),
            reverse=True,
        )
        
        # Add module overview
        for module in ranked_modules[:15]:
            desc = module.get("description", "")
            if desc:
                desc = desc.split("\n")[0][:100]
                lines.append(f"- **[{module['name']}]({module['path']})** - {desc}")
            else:
                lines.append(f"- **[{module['name']}]({module['path']})**")
        
        if len(modules) > 15:
            lines.append(f"- ... and {len(modules) - 15} more modules")
        
        lines.extend([
            "",
            "## 📊 Statistics",
            "",
            f"- **Files:** {structure.get('file_count', 'N/A')}",
            f"- **Modules:** {structure.get('module_count', 'N/A')}",
            f"- **Functions:** {structure.get('function_count', 'N/A')}",
            f"- **Classes:** {structure.get('class_count', 'N/A')}",
            "",
            "---",
            "",
            f"*Generated by [know](https://github.com/sushilk1991/know-cli) v{self.config.project.version}*",
            "",
            "Run `know update` to refresh this documentation.",
        ])
        
        content = "\n".join(lines)
        
        if output:
            path = Path(output)
        else:
            # Default to docs/arc.md instead of README.md
            path = self.output_dir / "arc.md"
        
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
        return path

    def _build_evidence_intro(self, structure: Dict[str, Any]) -> str:
        """Build a deterministic intro grounded in scanned repository evidence."""
        modules = structure.get("modules", [])
        file_count = self._to_int(structure.get("file_count"), len(modules))
        module_count = self._to_int(structure.get("module_count"), len(modules))

        lang_by_suffix = {
            ".py": "Python",
            ".ts": "TypeScript",
            ".tsx": "TSX",
            ".js": "JavaScript",
            ".jsx": "JSX",
            ".go": "Go",
            ".rs": "Rust",
            ".swift": "Swift",
        }

        lang_counts: Counter[str] = Counter()
        root_dir_counts: Counter[str] = Counter()
        for module in modules:
            path_str = str(module.get("path", ""))
            if not path_str:
                continue

            suffix = Path(path_str).suffix.lower()
            lang = lang_by_suffix.get(suffix)
            if lang:
                lang_counts[lang] += 1

            root_dir = path_str.split("/", 1)[0]
            if root_dir:
                root_dir_counts[root_dir] += 1

        language_summary = ", ".join(
            f"{lang} ({count})" for lang, count in lang_counts.most_common(4)
        ) or "unknown"
        area_summary = ", ".join(
            f"`{name}/` ({count})" for name, count in root_dir_counts.most_common(5)
        ) or "unknown"
        key_files = [f"`{p}`" for p in structure.get("key_files", [])[:5]]

        lines = [
            "Generated from static code scan (no model inference).",
            "",
            f"This repository contains {file_count} source files across {module_count} modules.",
            f"Primary languages: {language_summary}.",
            f"Primary source areas: {area_summary}.",
        ]
        if key_files:
            lines.append(f"Likely entry points: {', '.join(key_files)}.")

        return "\n".join(lines)
    
    def generate_readme(self, structure: Dict[str, Any], output: Optional[str] = None) -> Path:
        """Generate enhanced README.md (legacy, kept for backward compatibility)."""
        return self.generate_system_doc(structure, output)
    
    def generate_c4_diagram(
        self,
        structure: Dict[str, Any],
        output: Optional[str] = None
    ) -> Path:
        """Generate C4 architecture diagram."""
        if self.config.diagrams.format == "mermaid":
            return self._generate_mermaid_diagram(structure, output)
        else:
            return self._generate_c4_plantuml(structure, output)
    
    def _resolve_imports(self, structure: Dict[str, Any]) -> List[Tuple[str, str]]:
        """Use AST to resolve import relationships between project modules.
        
        Returns list of (source_module, target_module) edges.
        """
        # Build exact + short-name lookup tables.
        full_names: Set[str] = set()
        short_to_full: Dict[str, Set[str]] = defaultdict(set)
        for module in structure.get("modules", []):
            full_name = str(module.get("name", ""))
            if not full_name:
                continue
            full_names.add(full_name)
            short_name = full_name.split(".")[-1]
            short_to_full[short_name].add(full_name)
        
        edges: Set[Tuple[str, str]] = set()
        
        for module in structure.get("modules", []):
            source_name = str(module.get("name", ""))
            mod_path = self.config.root / str(module.get("path", ""))
            if not mod_path.exists() or not str(mod_path).endswith(".py"):
                continue
            
            try:
                source = mod_path.read_text(encoding="utf-8", errors="ignore")
                tree = ast.parse(source)
            except (SyntaxError, UnicodeDecodeError):
                continue
            
            for node in ast.walk(tree):
                targets: List[str] = []
                
                if isinstance(node, ast.Import):
                    for alias in node.names:
                        if alias.name:
                            targets.append(alias.name)  # keep fully-qualified module first
                            targets.append(alias.name.split(".")[-1])
                elif isinstance(node, ast.ImportFrom):
                    if node.module:
                        base = node.module
                        targets.append(base)  # keep fully-qualified module first
                        for alias in node.names:
                            if alias.name and alias.name != "*":
                                # Keep only fully-qualified module candidates to avoid
                                # symbol-vs-module false positives (e.g., `from x import config`).
                                targets.append(f"{base}.{alias.name}")
                
                for target in targets:
                    target_name: Optional[str] = None
                    if target in full_names:
                        target_name = target
                    else:
                        candidates = short_to_full.get(target, set())
                        # Avoid wrong links when short names are ambiguous.
                        if len(candidates) == 1:
                            target_name = next(iter(candidates))

                    if target_name and target_name != source_name:
                        edges.add((source_name, target_name))
        
        return sorted(edges)

    def _generate_mermaid_diagram(
        self,
        structure: Dict[str, Any],
        output: Optional[str] = None
    ) -> Path:
        """Generate Mermaid diagram with real import-based edges."""
        edges = self._resolve_imports(structure)
        modules = list(structure.get("modules", []))
        module_by_name = {str(m.get("name", "")): m for m in modules if m.get("name")}

        score: Counter[str] = Counter()
        for name, module in module_by_name.items():
            score[name] += self._to_int(module.get("function_count", 0))
            score[name] += self._to_int(module.get("class_count", 0))
        for src, tgt in edges:
            if src in module_by_name:
                score[src] += 3
            if tgt in module_by_name:
                score[tgt] += 2

        selected_names = sorted(
            module_by_name.keys(),
            key=lambda n: (score[n], n),
            reverse=True,
        )[:20]
        selected_set = set(selected_names)
        node_ids = {name: f"m{i}" for i, name in enumerate(selected_names)}
        short_name_counts: Counter[str] = Counter(name.split(".")[-1] for name in selected_names)

        def _label_for(name: str) -> str:
            parts = name.split(".")
            short = parts[-1]
            if short_name_counts[short] > 1 and len(parts) >= 2:
                short = f"{parts[-2]}.{short}"
            module = module_by_name.get(name, {})
            func_count = self._to_int(module.get("function_count", 0))
            class_count = self._to_int(module.get("class_count", 0))
            if func_count or class_count:
                return f"{short}\\n({func_count}f, {class_count}c)"
            return short
        
        lines = [
            "# Architecture Diagram",
            "",
            "```mermaid",
            "graph TB",
        ]

        for name in selected_names:
            label = _label_for(name).replace('"', "'")
            lines.append(f'    {node_ids[name]}["{label}"]')
        
        # Add edges
        filtered_edges = [
            (src, tgt)
            for src, tgt in edges
            if src in selected_set and tgt in selected_set and src != tgt
        ]
        if filtered_edges:
            lines.append("")
            for src, tgt in filtered_edges:
                lines.append(f"    {node_ids[src]} --> {node_ids[tgt]}")

        if len(module_by_name) > len(selected_names):
            lines.append("")
            lines.append(f"    %% Showing top {len(selected_names)} modules by code/import activity")
        
        lines.extend([
            "```",
            "",
            "*Generated by know*",
        ])
        
        content = "\n".join(lines)
        
        if output:
            path = Path(output)
        else:
            self.output_dir.mkdir(parents=True, exist_ok=True)
            path = self.output_dir / "architecture.md"
        
        path.write_text(content)
        return path
    
    def _generate_c4_plantuml(
        self,
        structure: Dict[str, Any],
        output: Optional[str] = None
    ) -> Path:
        """Generate C4 PlantUML diagram."""
        lines = [
            "# C4 Architecture",
            "",
            "```plantuml",
            "@startuml",
            "!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml",
            "",
            f"LAYOUT_WITH_LEGEND()",
            "",
            f'Title Container diagram for {self.config.project.name}',
            "",
        ]
        
        # Add containers
        for i, module in enumerate(structure.get("modules", [])[:10]):
            name = module['name'].split('.')[-1]
            lines.append(f'Container(container{i}, "{name}", "Python", "Module")')
        
        lines.extend([
            "",
            "@enduml",
            "```",
            "",
            "*Generated by know*",
        ])
        
        content = "\n".join(lines)
        
        if output:
            path = Path(output)
        else:
            self.output_dir.mkdir(parents=True, exist_ok=True)
            path = self.output_dir / "architecture-c4.md"
        
        path.write_text(content)
        return path
    
    def generate_component_diagram(
        self,
        structure: Dict[str, Any],
        output: Optional[str] = None
    ) -> Path:
        """Generate component-level diagram."""
        return self.generate_c4_diagram(structure, output)
    
    def generate_dependency_graph(
        self,
        structure: Dict[str, Any],
        output: Optional[str] = None
    ) -> Path:
        """Generate dependency graph with real import edges."""
        edges = self._resolve_imports(structure)
        modules = list(structure.get("modules", []))
        module_by_name = {str(m.get("name", "")): m for m in modules if m.get("name")}
        max_nodes = 15

        degree: Counter[str] = Counter()
        valid_edges = [
            (src, tgt)
            for src, tgt in edges
            if src in module_by_name and tgt in module_by_name and src != tgt
        ]
        for src, tgt in valid_edges:
            degree[src] += 1
            degree[tgt] += 1

        selected_set: Set[str] = set()
        # Keep edge endpoints first so we don't hide all real links.
        ranked_edges = sorted(
            valid_edges,
            key=lambda e: (degree[e[0]] + degree[e[1]], e[0], e[1]),
            reverse=True,
        )
        for src, tgt in ranked_edges:
            if len(selected_set) < max_nodes:
                selected_set.add(src)
            if len(selected_set) < max_nodes:
                selected_set.add(tgt)
            if len(selected_set) >= max_nodes:
                break

        if len(selected_set) < max_nodes:
            for name in sorted(module_by_name.keys(), key=lambda n: (degree[n], n), reverse=True):
                selected_set.add(name)
                if len(selected_set) >= max_nodes:
                    break

        selected_names = sorted(selected_set, key=lambda n: (degree[n], n), reverse=True)
        selected_set = set(selected_names)
        node_ids = {name: f"d{i}" for i, name in enumerate(selected_names)}
        short_name_counts: Counter[str] = Counter(name.split(".")[-1] for name in selected_names)

        def _label_for(name: str) -> str:
            parts = name.split(".")
            short = parts[-1]
            if short_name_counts[short] > 1 and len(parts) >= 2:
                short = f"{parts[-2]}.{short}"
            return short
        
        lines = [
            "# Dependency Graph",
            "",
            "```mermaid",
            "graph LR",
        ]
        
        # Add modules as nodes
        for name in selected_names:
            label = _label_for(name).replace('"', "'")
            lines.append(f'    {node_ids[name]}["{label}"]')
        
        # Add edges
        filtered_edges = [
            (src, tgt)
            for src, tgt in valid_edges
            if src in selected_set and tgt in selected_set and src != tgt
        ]
        if filtered_edges:
            lines.append("")
            for src, tgt in filtered_edges:
                lines.append(f"    {node_ids[src]} --> {node_ids[tgt]}")

        if len(module_by_name) > len(selected_names):
            lines.append("")
            lines.append(
                f"    %% Showing {len(selected_names)} of {len(module_by_name)} modules; prioritizing connected nodes"
            )
        
        lines.extend([
            "```",
            "",
            "*Generated by know*",
        ])
        
        content = "\n".join(lines)
        
        if output:
            path = Path(output)
        else:
            self.output_dir.mkdir(parents=True, exist_ok=True)
            path = self.output_dir / "dependencies.md"
        
        path.write_text(content)
        return path
    
    def generate_openapi(
        self,
        routes: List["APIRoute"],
        output: Optional[str] = None
    ) -> Path:
        """Generate OpenAPI specification."""
        spec = {
            "openapi": "3.0.0",
            "info": {
                "title": self.config.project.name,
                "version": self.config.project.version,
                "description": self.config.project.description
            },
            "paths": {}
        }
        
        for route in routes:
            path = route.path
            if path not in spec["paths"]:
                spec["paths"][path] = {}
            
            method = route.method.lower()
            spec["paths"][path][method] = {
                "summary": route.handler,
                "description": route.docstring or "",
                "responses": {
                    "200": {
                        "description": "Success"
                    }
                }
            }
        
        content = json.dumps(spec, indent=2)
        
        if output:
            path = Path(output)
        else:
            self.output_dir.mkdir(parents=True, exist_ok=True)
            path = self.output_dir / "openapi.json"
        
        path.write_text(content)
        return path
    
    def generate_postman(
        self,
        routes: List["APIRoute"],
        output: Optional[str] = None
    ) -> Path:
        """Generate Postman collection."""
        collection = {
            "info": {
                "name": self.config.project.name,
                "description": self.config.project.description,
                "schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
            },
            "item": []
        }
        
        for route in routes:
            item = {
                "name": route.handler,
                "request": {
                    "method": route.method,
                    "header": [],
                    "url": {
                        "raw": route.path,
                        "path": route.path.split("/")
                    },
                    "description": route.docstring or ""
                }
            }
            collection["item"].append(item)
        
        content = json.dumps(collection, indent=2)
        
        if output:
            path = Path(output)
        else:
            self.output_dir.mkdir(parents=True, exist_ok=True)
            path = self.output_dir / "postman-collection.json"
        
        path.write_text(content)
        return path
    
    def generate_api_markdown(
        self,
        routes: List["APIRoute"],
        output: Optional[str] = None
    ) -> Path:
        """Generate API documentation in Markdown."""
        lines = [
            "# API Documentation",
            "",
        ]
        
        # Group by path
        by_path: Dict[str, List["APIRoute"]] = {}
        for route in routes:
            if route.path not in by_path:
                by_path[route.path] = []
            by_path[route.path].append(route)
        
        for path, path_routes in sorted(by_path.items()):
            lines.append(f"## `{path}`")
            lines.append("")
            
            for route in path_routes:
                lines.append(f"### {route.method}")
                lines.append("")
                lines.append(f"**Handler:** `{route.handler}`")
                lines.append("")
                
                if route.docstring:
                    lines.append(route.docstring)
                    lines.append("")
                
                lines.append(f"*File: `{route.file_path}:{route.line_number}`*")
                lines.append("")
        
        content = "\n".join(lines)
        
        if output:
            path = Path(output)
        else:
            self.output_dir.mkdir(parents=True, exist_ok=True)
            path = self.output_dir / "api.md"
        
        path.write_text(content)
        return path
    
    def save_onboarding(
        self,
        guide: str,
        audience: str,
        format: str = "markdown"
    ) -> Path:
        """Save onboarding guide."""
        self.output_dir.mkdir(parents=True, exist_ok=True)
        
        safe_audience = audience.replace(" ", "_").lower()
        
        if format == "markdown":
            path = self.output_dir / f"onboarding-{safe_audience}.md"
            path.write_text(guide)
        elif format == "html":
            path = self.output_dir / f"onboarding-{safe_audience}.html"
            html = f"""<!DOCTYPE html>
<html>
<head><title>Onboarding - {audience}</title></head>
<body>
{guide}
</body>
</html>"""
            path.write_text(html)
        else:
            path = self.output_dir / f"onboarding-{safe_audience}.md"
            path.write_text(guide)
        
        return path
    
    def generate_onboarding(
        self,
        structure: Dict[str, Any]
    ) -> Path:
        """Generate default onboarding guide."""
        api_key = os.environ.get(self.config.ai.api_key_env)
        if not api_key:
            guide = self._fallback_onboarding_guide(structure)
        else:
            from know.ai import AISummarizer
            ai = AISummarizer(self.config)
            guide = ai.generate_onboarding_guide(structure, "new team members")
        
        return self.save_onboarding(guide, "new-devs")

    def _fallback_onboarding_guide(self, structure: Dict[str, Any]) -> str:
        """Deterministic onboarding guide when AI is unavailable."""
        modules = structure.get("modules", [])
        key_files = [f"`{p}`" for p in structure.get("key_files", [])[:8]]
        lines = [
            "# Onboarding Guide",
            "",
            "## 1. What This Repo Contains",
            "",
            f"- Source files: {structure.get('file_count', len(modules))}",
            f"- Modules: {structure.get('module_count', len(modules))}",
            f"- Functions: {structure.get('function_count', 0)}",
            f"- Classes: {structure.get('class_count', 0)}",
            "",
            "## 2. Start Here",
            "",
        ]
        if key_files:
            lines.extend([f"- {entry}" for entry in key_files[:5]])
        else:
            lines.append("- Inspect `docs/arc.md` and `docs/architecture.md` first.")

        lines.extend(
            [
                "",
                "## 3. Development Workflow",
                "",
                "1. Run tests for impacted areas first.",
                "2. Use `know map` + `know context` to identify edit targets.",
                "3. Re-run docs with `know update --only system` after structural changes.",
            ]
        )
        return "\n".join(lines) + "\n"
