"""Git hook management."""

import os
import stat
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from know.config import Config


POST_COMMIT_HOOK = '''#!/bin/bash
# Auto-generated by know - updates documentation on commit

# Check if know is available
if command -v know &> /dev/null; then
    echo "🧠 Updating documentation..."
    know update --quiet
    
    # Check if docs were updated
    if git diff --quiet HEAD docs/ 2>/dev/null; then
        echo "✓ Documentation up to date"
    else
        git add docs/
        git commit --amend --no-edit --quiet
        echo "✓ Documentation updated and amended"
    fi
fi
'''

PRE_COMMIT_HOOK = '''#!/bin/bash
# Auto-generated by know - validates documentation before commit

# Check if know config exists
if [ -f ".know/config.yaml" ]; then
    echo "🧠 Validating documentation..."
    
    # You can add validation logic here
    # For now, just check that docs exist
    if [ ! -d "docs" ] && [ ! -f "README.md" ]; then
        echo "⚠ Warning: No documentation found. Run 'know init' to generate."
    fi
fi
'''


class GitHookManager:
    """Manages git hooks for know integration."""
    
    def __init__(self, config: "Config"):
        self.config = config
        self.hooks_dir = config.root / ".git" / "hooks"
    
    def install_post_commit(self) -> bool:
        """Install post-commit hook."""
        if not self._check_git_repo():
            print("✗ Not a git repository")
            return False
        
        hook_path = self.hooks_dir / "post-commit"
        
        # Check if hook already exists
        if hook_path.exists():
            content = hook_path.read_text()
            if "know" in content:
                print("⚠ know hook already installed")
                return True
            
            # Backup existing hook
            backup = hook_path.with_suffix(".backup")
            hook_path.rename(backup)
            print(f"ℹ Backed up existing hook to {backup}")
        
        # Write hook
        hook_path.write_text(POST_COMMIT_HOOK)
        
        # Make executable
        hook_path.chmod(
            hook_path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH
        )
        
        print("✓ Post-commit hook installed")
        print("  Documentation will update automatically after each commit")
        return True
    
    def uninstall_post_commit(self) -> bool:
        """Remove post-commit hook."""
        if not self._check_git_repo():
            print("✗ Not a git repository")
            return False
        
        hook_path = self.hooks_dir / "post-commit"
        
        if not hook_path.exists():
            print("⚠ No post-commit hook found")
            return True
        
        content = hook_path.read_text()
        if "know" not in content:
            print("⚠ Hook doesn't appear to be from know, not removing")
            return False
        
        hook_path.unlink()
        
        # Restore backup if exists
        backup = hook_path.with_suffix(".backup")
        if backup.exists():
            backup.rename(hook_path)
            print(f"✓ Restored backup hook")
        
        print("✓ Post-commit hook removed")
        return True
    
    def install_pre_commit(self) -> bool:
        """Install pre-commit hook."""
        if not self._check_git_repo():
            print("✗ Not a git repository")
            return False
        
        hook_path = self.hooks_dir / "pre-commit"
        
        if hook_path.exists():
            content = hook_path.read_text()
            if "know" in content:
                print("⚠ know hook already installed")
                return True
        
        hook_path.write_text(PRE_COMMIT_HOOK)
        hook_path.chmod(
            hook_path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH
        )
        
        print("✓ Pre-commit hook installed")
        return True
    
    def uninstall_pre_commit(self) -> bool:
        """Remove pre-commit hook."""
        if not self._check_git_repo():
            print("✗ Not a git repository")
            return False
        
        hook_path = self.hooks_dir / "pre-commit"
        
        if not hook_path.exists():
            print("⚠ No pre-commit hook found")
            return True
        
        content = hook_path.read_text()
        if "know" not in content:
            print("⚠ Hook doesn't appear to be from know, not removing")
            return False
        
        hook_path.unlink()
        print("✓ Pre-commit hook removed")
        return True
    
    def _check_git_repo(self) -> bool:
        """Check if current directory is a git repository."""
        git_dir = self.config.root / ".git"
        return git_dir.exists() and git_dir.is_dir()
    
    def status(self) -> None:
        """Show git hook status."""
        if not self._check_git_repo():
            print("✗ Not a git repository")
            return
        
        print("Git Hooks Status:")
        print()
        
        for hook_name in ["post-commit", "pre-commit"]:
            hook_path = self.hooks_dir / hook_name
            
            if hook_path.exists():
                content = hook_path.read_text()
                if "know" in content:
                    print(f"  ✓ {hook_name}: installed by know")
                else:
                    print(f"  ⚠ {hook_name}: exists (not from know)")
            else:
                print(f"  ✗ {hook_name}: not installed")
