"""Git hook management."""

import stat
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from know.config import Config


_KNOW_MARKER = "Auto-generated by know"

POST_COMMIT_HOOK = """#!/bin/bash
# Auto-generated by know - refresh index and docs after commit

if command -v know > /dev/null 2>&1; then
    echo "know: refreshing index cache..."
    know warm --json > /dev/null 2>&1 || true
    echo "know: updating docs..."
    know update --quiet > /dev/null 2>&1 || true
fi
"""

POST_MERGE_HOOK = """#!/bin/bash
# Auto-generated by know - refresh index after merge

if command -v know > /dev/null 2>&1; then
    echo "know: refreshing index cache..."
    know warm --json > /dev/null 2>&1 || true
fi
"""

POST_CHECKOUT_HOOK = """#!/bin/bash
# Auto-generated by know - refresh index after checkout

if command -v know > /dev/null 2>&1; then
    know warm --json > /dev/null 2>&1 || true
fi
"""

PRE_COMMIT_HOOK = '''#!/bin/bash
# Auto-generated by know - validates documentation before commit

# Check if know config exists
if [ -f ".know/config.yaml" ]; then
    echo "🧠 Validating documentation..."
    
    # Check that docs directory exists (arc.md is the primary output)
    DOCS_DIR=$(grep -oP 'directory:\\s*\\K.*' .know/config.yaml 2>/dev/null || echo "docs")
    if [ ! -d "$DOCS_DIR" ]; then
        echo "⚠ Warning: No documentation found. Run 'know init' to generate."
    fi
fi
'''


class GitHookManager:
    """Manages git hooks for know integration."""

    def __init__(self, config: "Config"):
        self.config = config
        self.hooks_dir = config.root / ".git" / "hooks"

    def _install_named_hook(self, hook_name: str, content: str) -> dict:
        if not self._check_git_repo():
            return {"hook": hook_name, "status": "not_git_repo"}

        hook_path = self.hooks_dir / hook_name
        backup_path = None
        if hook_path.exists():
            existing = hook_path.read_text()
            if _KNOW_MARKER in existing:
                return {"hook": hook_name, "status": "already_installed"}

            backup = hook_path.with_suffix(".backup")
            hook_path.rename(backup)
            backup_path = backup

        hook_path.write_text(content)
        hook_path.chmod(
            hook_path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH
        )
        payload = {"hook": hook_name, "status": "installed"}
        if backup_path is not None:
            payload["backup_path"] = str(backup_path)
        return payload

    def _uninstall_named_hook(self, hook_name: str) -> dict:
        if not self._check_git_repo():
            return {"hook": hook_name, "status": "not_git_repo"}

        hook_path = self.hooks_dir / hook_name
        if not hook_path.exists():
            return {"hook": hook_name, "status": "missing"}

        content = hook_path.read_text()
        if _KNOW_MARKER not in content:
            return {"hook": hook_name, "status": "skipped_non_know"}

        hook_path.unlink()
        restored_backup = False
        backup = hook_path.with_suffix(".backup")
        if backup.exists():
            backup.rename(hook_path)
            restored_backup = True

        payload = {"hook": hook_name, "status": "removed"}
        if restored_backup:
            payload["restored_backup"] = True
        return payload

    def install_post_commit(self) -> dict:
        """Install post-commit hook."""
        return self._install_named_hook("post-commit", POST_COMMIT_HOOK)

    def uninstall_post_commit(self) -> dict:
        """Remove post-commit hook."""
        return self._uninstall_named_hook("post-commit")

    def install_post_merge(self) -> dict:
        """Install post-merge hook."""
        return self._install_named_hook("post-merge", POST_MERGE_HOOK)

    def uninstall_post_merge(self) -> dict:
        """Remove post-merge hook."""
        return self._uninstall_named_hook("post-merge")

    def install_post_checkout(self) -> dict:
        """Install post-checkout hook."""
        return self._install_named_hook("post-checkout", POST_CHECKOUT_HOOK)

    def uninstall_post_checkout(self) -> dict:
        """Remove post-checkout hook."""
        return self._uninstall_named_hook("post-checkout")

    def install_pre_commit(self) -> dict:
        """Install pre-commit hook."""
        return self._install_named_hook("pre-commit", PRE_COMMIT_HOOK)

    def uninstall_pre_commit(self) -> dict:
        """Remove pre-commit hook."""
        return self._uninstall_named_hook("pre-commit")

    def _check_git_repo(self) -> bool:
        """Check if current directory is a git repository."""
        git_dir = self.config.root / ".git"
        return git_dir.exists() and git_dir.is_dir()

    def status(self) -> dict[str, str]:
        """Return git hook status map."""
        if not self._check_git_repo():
            return {}

        statuses: dict[str, str] = {}
        for hook_name in ("post-commit", "post-merge", "post-checkout", "pre-commit"):
            hook_path = self.hooks_dir / hook_name
            if hook_path.exists():
                content = hook_path.read_text()
                if _KNOW_MARKER in content:
                    statuses[hook_name] = "installed_by_know"
                else:
                    statuses[hook_name] = "present_other"
            else:
                statuses[hook_name] = "missing"
        return statuses
