name: 'Know CLI Documentation'
author: 'Sushil Kumar'
description: 'Auto-generate and update documentation for your codebase using know-cli'
branding:
  icon: 'book'
  color: 'blue'

inputs:
  api-key:
    description: 'Anthropic API key for AI-powered documentation'
    required: true
  output-dir:
    description: 'Directory for generated documentation'
    required: false
    default: 'docs'
  comment-on-pr:
    description: 'Post documentation summary as PR comment'
    required: false
    default: 'true'
  generate-on-push:
    description: 'Generate docs on push to main'
    required: false
    default: 'true'
  fail-on-error:
    description: 'Fail the workflow if docs generation fails'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install know-cli
      shell: bash
      run: |
        pip install know-cli

    - name: Generate documentation
      shell: bash
      env:
        ANTHROPIC_API_KEY: ${{ inputs.api-key }}
      run: |
        echo "Generating documentation..."
        know init || true
        know digest --for-llm
        know update --only system
        know update --only diagrams
      continue-on-error: ${{ inputs.fail-on-error == 'false' }}

    - name: Check for changes
      id: changes
      shell: bash
      run: |
        if [ -n "$(git status --porcelain docs/ .know/)" ]; then
          echo "has_changes=true" >> $GITHUB_OUTPUT
        else
          echo "has_changes=false" >> $GITHUB_OUTPUT
        fi

    - name: Commit documentation changes
      if: steps.changes.outputs.has_changes == 'true'
      shell: bash
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/ .know/ || true
        git commit -m "docs: Auto-update documentation via know-cli" || true
        git push || true
      continue-on-error: true

    - name: Post PR comment
      if: github.event_name == 'pull_request' && inputs.comment-on-pr == 'true'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const path = require('path');
          
          // Read digest if available
          let digestContent = '';
          const digestPath = path.join('${{ inputs.output-dir }}', 'digest-llm.md');
          if (fs.existsSync(digestPath)) {
            digestContent = fs.readFileSync(digestPath, 'utf8').slice(0, 3000);
          }
          
          const body = `## 📚 Documentation Update
          
          This PR has been analyzed by **know-cli**.
          
          ### Summary
          - Documentation auto-generated and committed
          - Files updated in \`${{ inputs.output-dir }}/\`
          
          ${digestContent ? `### Codebase Context\n\n\`\`\`markdown\n${digestContent}\n\`\`\`` : ''}
          
          ---
          *Generated by [know-cli](https://github.com/sushilk1991/know-cli)*`;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: body
          });
